from _typeshed import Incomplete

class ResourceIdentifierTransformer:
    session: Incomplete
    def __init__(self, session) -> None: ...
    def encode(self, resource_identifier, context: Incomplete | None = None): ...
    def decode(self, resource_identifier, context: Incomplete | None = None): ...
