from _typeshed import Incomplete

scenario_name: str

class ConfigureCentralizedStorageScenario:
    logger: Incomplete
    def __init__(self) -> None: ...
    @property
    def storage_scenario(self): ...
    @property
    def existing_centralized_storage_configuration(self): ...
    def configure_scenario(self, event): ...
    def discover_centralized_scenario(self, event): ...
    session: Incomplete
    def register(self, session) -> None: ...

class ActivateCentralizedStorageScenario:
    logger: Incomplete
    def __init__(self) -> None: ...
    def activate(self, event) -> None: ...
    session: Incomplete
    def register(self, session) -> None: ...

def register(session) -> None: ...
def register_configuration(session) -> None: ...
