import ftrack_api.collection
from _typeshed import Incomplete

logger: Incomplete

def merge_references(function): ...

class Attributes:
    def __init__(self, attributes: Incomplete | None = None) -> None: ...
    def add(self, attribute) -> None: ...
    def remove(self, attribute) -> None: ...
    def get(self, name): ...
    def keys(self): ...
    def __contains__(self, item) -> bool: ...
    def __iter__(self): ...
    def __len__(self) -> int: ...

class Attribute:
    default_value: Incomplete
    def __init__(self, name, default_value=..., mutable: bool = True, computed: bool = False) -> None: ...
    def get_entity_storage(self, entity): ...
    @property
    def name(self): ...
    @property
    def mutable(self): ...
    @property
    def computed(self): ...
    def get_value(self, entity): ...
    def get_local_value(self, entity): ...
    def get_remote_value(self, entity): ...
    def set_local_value(self, entity, value) -> None: ...
    def set_remote_value(self, entity, value) -> None: ...
    def populate_remote_value(self, entity) -> None: ...
    def is_modified(self, entity): ...
    def is_set(self, entity): ...

class ScalarAttribute(Attribute):
    data_type: Incomplete
    def __init__(self, name, data_type, **kw) -> None: ...

class ReferenceAttribute(Attribute):
    entity_type: Incomplete
    def __init__(self, name, entity_type, **kw) -> None: ...
    def populate_remote_value(self, entity) -> None: ...
    def is_modified(self, entity): ...
    def get_value(self, entity): ...

class AbstractCollectionAttribute(Attribute):
    collection_class: Incomplete
    def get_value(self, entity): ...
    def set_local_value(self, entity, value) -> None: ...
    def set_remote_value(self, entity, value) -> None: ...

class CollectionAttribute(AbstractCollectionAttribute):
    collection_class = ftrack_api.collection.Collection

class KeyValueMappedCollectionAttribute(AbstractCollectionAttribute):
    collection_class = ftrack_api.collection.KeyValueMappedCollectionProxy
    creator: Incomplete
    key_attribute: Incomplete
    value_attribute: Incomplete
    def __init__(self, name, creator, key_attribute, value_attribute, **kw) -> None: ...

class CustomAttributeCollectionAttribute(AbstractCollectionAttribute):
    collection_class = ftrack_api.collection.CustomAttributeCollectionProxy
