import abc
from _typeshed import Incomplete

class Cache(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def get(self, key): ...
    @abc.abstractmethod
    def set(self, key, value): ...
    @abc.abstractmethod
    def remove(self, key): ...
    def keys(self) -> None: ...
    def values(self): ...
    def clear(self, pattern: Incomplete | None = None) -> None: ...

class ProxyCache(Cache):
    proxied: Incomplete
    def __init__(self, proxied) -> None: ...
    def get(self, key): ...
    def set(self, key, value): ...
    def remove(self, key): ...
    def keys(self): ...

class LayeredCache(Cache):
    caches: Incomplete
    def __init__(self, caches) -> None: ...
    def get(self, key): ...
    def set(self, key, value) -> None: ...
    def remove(self, key) -> None: ...
    def keys(self): ...

class MemoryCache(Cache):
    def __init__(self) -> None: ...
    def get(self, key): ...
    def set(self, key, value) -> None: ...
    def remove(self, key) -> None: ...
    def keys(self): ...

class FileCache(Cache):
    path: Incomplete
    def __init__(self, path) -> None: ...
    def get(self, key): ...
    def set(self, key, value) -> None: ...
    def remove(self, key) -> None: ...
    def keys(self): ...

class SerialisedCache(ProxyCache):
    encode: Incomplete
    decode: Incomplete
    def __init__(self, proxied, encode: Incomplete | None = None, decode: Incomplete | None = None) -> None: ...
    def get(self, key): ...
    def set(self, key, value) -> None: ...

class KeyMaker(metaclass=abc.ABCMeta):
    item_separator: str
    def __init__(self) -> None: ...
    def key(self, *items): ...

class StringKeyMaker(KeyMaker): ...

class ObjectKeyMaker(KeyMaker):
    item_separator: bytes
    mapping_identifier: bytes
    mapping_pair_separator: bytes
    iterable_identifier: bytes
    name_identifier: bytes
    def __init__(self) -> None: ...

class Memoiser:
    cache: Incomplete
    key_maker: Incomplete
    return_copies: Incomplete
    def __init__(self, cache: Incomplete | None = None, key_maker: Incomplete | None = None, return_copies: bool = True) -> None: ...
    def call(self, function, args: Incomplete | None = None, kw: Incomplete | None = None): ...

def memoise_decorator(memoiser): ...

memoiser: Incomplete
memoise: Incomplete
