import abc
import collections.abc
import ftrack_api.cache
from _typeshed import Incomplete

class Collection(collections.abc.MutableSequence):
    entity: Incomplete
    attribute: Incomplete
    mutable: bool
    def __init__(self, entity, attribute, mutable: bool = True, data: Incomplete | None = None) -> None: ...
    def __copy__(self): ...
    def insert(self, index, item) -> None: ...
    def __contains__(self, value) -> bool: ...
    def __getitem__(self, index): ...
    def __setitem__(self, index, item) -> None: ...
    def __delitem__(self, index) -> None: ...
    def __len__(self) -> int: ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...

class MappedCollectionProxy(collections.abc.MutableMapping, metaclass=abc.ABCMeta):
    logger: Incomplete
    collection: Incomplete
    def __init__(self, collection) -> None: ...
    def __copy__(self): ...
    @property
    def mutable(self): ...
    @mutable.setter
    def mutable(self, value) -> None: ...
    @property
    def attribute(self): ...
    @attribute.setter
    def attribute(self, value) -> None: ...

class KeyValueMappedCollectionProxy(MappedCollectionProxy):
    creator: Incomplete
    key_attribute: Incomplete
    value_attribute: Incomplete
    def __init__(self, collection, creator, key_attribute, value_attribute) -> None: ...
    def __getitem__(self, key): ...
    def __setitem__(self, key, value) -> None: ...
    def __delitem__(self, key) -> None: ...
    def __iter__(self): ...
    def __len__(self) -> int: ...
    def keys(self): ...

class PerSessionDefaultKeyMaker(ftrack_api.cache.KeyMaker): ...

memoise_session: Incomplete

class CustomAttributeCollectionProxy(MappedCollectionProxy):
    key_attribute: str
    value_attribute: str
    def __init__(self, collection) -> None: ...
    def get_configuration_id_from_key(self, key): ...
    def __getitem__(self, key): ...
    def __setitem__(self, key, value) -> None: ...
    def __delitem__(self, key) -> None: ...
    def __eq__(self, collection): ...
    def __iter__(self): ...
    def __len__(self) -> int: ...
