from _typeshed import Incomplete

class Operations:
    def __init__(self) -> None: ...
    def clear(self) -> None: ...
    def push(self, operation) -> None: ...
    def pop(self): ...
    def __len__(self) -> int: ...
    def __iter__(self): ...

class Operation: ...

class CreateEntityOperation(Operation):
    entity_type: Incomplete
    entity_key: Incomplete
    entity_data: Incomplete
    def __init__(self, entity_type, entity_key, entity_data) -> None: ...

class UpdateEntityOperation(Operation):
    entity_type: Incomplete
    entity_key: Incomplete
    attribute_name: Incomplete
    old_value: Incomplete
    new_value: Incomplete
    def __init__(
        self, entity_type, entity_key, attribute_name, old_value, new_value
    ) -> None: ...

class DeleteEntityOperation(Operation):
    entity_type: Incomplete
    entity_key: Incomplete
    def __init__(self, entity_type, entity_key) -> None: ...
