import abc

class Accessor(metaclass=abc.ABCMeta):
    def __init__(self) -> None: ...
    @abc.abstractmethod
    def list(self, resource_identifier): ...
    @abc.abstractmethod
    def exists(self, resource_identifier): ...
    @abc.abstractmethod
    def is_file(self, resource_identifier): ...
    @abc.abstractmethod
    def is_container(self, resource_identifier): ...
    @abc.abstractmethod
    def is_sequence(self, resource_identifier): ...
    @abc.abstractmethod
    def open(self, resource_identifier, mode: str = 'rb'): ...
    @abc.abstractmethod
    def remove(self, resource_identifier): ...
    @abc.abstractmethod
    def make_container(self, resource_identifier, recursive: bool = True): ...
    @abc.abstractmethod
    def get_container(self, resource_identifier): ...
    def remove_container(self, resource_identifier): ...
    def get_filesystem_path(self, resource_identifier) -> None: ...
    def get_url(self, resource_identifier) -> None: ...
