from ..data import String as String
from .base import Accessor as Accessor
from _typeshed import Incomplete

class ServerFile(String):
    mode: Incomplete
    resource_identifier: Incomplete
    def __init__(self, resource_identifier, session, mode: str = "rb") -> None: ...
    def flush(self) -> None: ...
    def read(self, limit: Incomplete | None = None): ...

class _ServerAccessor(Accessor):
    def __init__(self, session, **kw) -> None: ...
    def open(self, resource_identifier, mode: str = "rb"): ...
    def remove(self, resourceIdentifier) -> None: ...
    def get_container(self, resource_identifier) -> None: ...
    def make_container(self, resource_identifier, recursive: bool = True) -> None: ...
    def list(self, resource_identifier) -> None: ...
    def exists(self, resource_identifier): ...
    def is_file(self, resource_identifier) -> None: ...
    def is_container(self, resource_identifier) -> None: ...
    def is_sequence(self, resource_identifier) -> None: ...
    def get_url(self, resource_identifier): ...
    def get_thumbnail_url(
        self, resource_identifier, size: Incomplete | None = None
    ): ...
