from _typeshed import Incomplete
from abc import ABCMeta, abstractmethod

class Data(metaclass=ABCMeta):
    closed: bool
    def __init__(self) -> None: ...
    @abstractmethod
    def read(self, limit: Incomplete | None = None): ...
    @abstractmethod
    def write(self, content): ...
    def flush(self) -> None: ...
    def seek(self, offset, whence=...) -> None: ...
    def tell(self) -> None: ...
    def close(self) -> None: ...

class FileWrapper(Data):
    wrapped_file: Incomplete
    def __init__(self, wrapped_file) -> None: ...
    def read(self, limit: Incomplete | None = None): ...
    def write(self, content) -> None: ...
    def flush(self) -> None: ...
    def seek(self, offset, whence=...) -> None: ...
    def tell(self): ...
    def close(self) -> None: ...

class File(FileWrapper):
    def __init__(self, path, mode: str = "rb") -> None: ...

class String(FileWrapper):
    is_binary: bool
    def __init__(self, content: Incomplete | None = None) -> None: ...
    def write(self, content) -> None: ...
    def read(self, limit: Incomplete | None = None): ...
