import collections.abc
from _typeshed import Incomplete

class QueryResult(collections.abc.Sequence):
    OFFSET_EXPRESSION: Incomplete
    LIMIT_EXPRESSION: Incomplete
    def __init__(self, session, expression, page_size: int = 500) -> None: ...
    def __getitem__(self, index): ...
    def __len__(self) -> int: ...
    def all(self): ...
    def one(self): ...
    def first(self): ...
