import collections.abc
import requests.auth
from _typeshed import Incomplete

class SessionAuthentication(requests.auth.AuthBase):
    api_key: Incomplete
    api_user: Incomplete
    def __init__(self, api_key, api_user) -> None: ...
    def __call__(self, request): ...

class Session:
    logger: Incomplete
    recorded_operations: Incomplete
    cache_key_maker: Incomplete
    cache: Incomplete
    merge_lock: Incomplete
    request_timeout: Incomplete
    schemas: Incomplete
    types: Incomplete
    def __init__(
        self,
        server_url: Incomplete | None = None,
        api_key: Incomplete | None = None,
        api_user: Incomplete | None = None,
        auto_populate: bool = True,
        plugin_paths: Incomplete | None = None,
        cache: Incomplete | None = None,
        cache_key_maker: Incomplete | None = None,
        auto_connect_event_hub: bool = False,
        schema_cache_path: Incomplete | None = None,
        plugin_arguments: Incomplete | None = None,
        timeout: int = 60,
        cookies: Incomplete | None = None,
        headers: Incomplete | None = None,
        strict_api: bool = False,
    ) -> None: ...
    def __enter__(self): ...
    def __exit__(
        self,
        exception_type: type[BaseException] | None,
        exception_value: BaseException | None,
        traceback: types.TracebackType | None,
    ) -> None: ...
    @property
    def auto_populate(self): ...
    @auto_populate.setter
    def auto_populate(self, value) -> None: ...
    @property
    def record_operations(self): ...
    @record_operations.setter
    def record_operations(self, value) -> None: ...
    @property
    def closed(self): ...
    @property
    def server_information(self): ...
    @property
    def server_url(self): ...
    @property
    def api_user(self): ...
    @property
    def api_key(self): ...
    @property
    def event_hub(self): ...
    def check_server_compatibility(self) -> None: ...
    def close(self) -> None: ...
    def reset(self) -> None: ...
    def auto_populating(self, auto_populate): ...
    def operation_recording(self, record_operations): ...
    @property
    def created(self): ...
    @property
    def modified(self): ...
    @property
    def deleted(self): ...
    def reset_remote(self, reset_type, entity: Incomplete | None = None): ...
    def create(
        self, entity_type, data: Incomplete | None = None, reconstructing: bool = False
    ): ...
    def ensure(self, entity_type, data, identifying_keys: Incomplete | None = None): ...
    def delete(self, entity) -> None: ...
    def get(self, entity_type, entity_key): ...
    def query(self, expression, page_size: int = 500): ...
    def merge(self, value, merged: Incomplete | None = None): ...
    def populate(self, entities, projections) -> None: ...
    def commit(self) -> None: ...
    def rollback(self) -> None: ...
    def call(self, data): ...
    def encode(self, data, entity_attribute_strategy: str = "set_only"): ...
    def entity_reference(self, entity): ...
    def decode(self, string): ...
    def pick_location(self, component: Incomplete | None = None): ...
    def pick_locations(self, components): ...
    def create_component(
        self, path, data: Incomplete | None = None, location: str = "auto"
    ): ...
    def get_component_availability(
        self, component, locations: Incomplete | None = None
    ): ...
    def get_component_availabilities(
        self, components, locations: Incomplete | None = None
    ): ...
    def get_widget_url(
        self, name, entity: Incomplete | None = None, theme: Incomplete | None = None
    ): ...
    def encode_media(
        self, media, version_id: Incomplete | None = None, keep_original: str = "auto"
    ): ...
    def get_upload_metadata(
        self, component_id, file_name, file_size, checksum: Incomplete | None = None
    ): ...
    def send_user_invite(self, user) -> None: ...
    def send_user_invites(self, users) -> None: ...
    def send_review_session_invite(self, invitee) -> None: ...
    def send_review_session_invites(self, invitees) -> None: ...

class AutoPopulatingContext:
    def __init__(self, session, auto_populate) -> None: ...
    def __enter__(self) -> None: ...
    def __exit__(
        self,
        exception_type: type[BaseException] | None,
        exception_value: BaseException | None,
        traceback: types.TracebackType | None,
    ) -> None: ...

class OperationRecordingContext:
    def __init__(self, session, record_operations) -> None: ...
    def __enter__(self) -> None: ...
    def __exit__(
        self,
        exception_type: type[BaseException] | None,
        exception_value: BaseException | None,
        traceback: types.TracebackType | None,
    ) -> None: ...

class OperationPayload(collections.abc.MutableMapping):
    def __init__(self, *args, **kwargs) -> None: ...
    def __getitem__(self, key): ...
    def __setitem__(self, key, value) -> None: ...
    def __delitem__(self, key) -> None: ...
    def __iter__(self): ...
    def __len__(self) -> int: ...
