import abc
import collections.abc
from _typeshed import Incomplete

class _EntityBase: ...
class DynamicEntityTypeMetaclass(abc.ABCMeta): ...

class Entity(_EntityBase, collections.abc.MutableMapping, metaclass=DynamicEntityTypeMetaclass):
    entity_type: str
    attributes: Incomplete
    primary_key_attributes: Incomplete
    default_projections: Incomplete
    logger: Incomplete
    session: Incomplete
    def __init__(self, session, data: Incomplete | None = None, reconstructing: bool = False) -> None: ...
    def __hash__(self): ...
    def __eq__(self, other): ...
    def __getitem__(self, key): ...
    def __setitem__(self, key, value) -> None: ...
    def __delitem__(self, key) -> None: ...
    def __iter__(self): ...
    def __len__(self) -> int: ...
    def values(self): ...
    def items(self): ...
    def clear(self) -> None: ...
    def merge(self, entity, merged: Incomplete | None = None): ...
