import ftrack_api.cache
from _typeshed import Incomplete

class Factory:
    logger: Incomplete
    def __init__(self) -> None: ...
    def create(self, schema, bases: Incomplete | None = None): ...
    def create_scalar_attribute(self, class_name, name, mutable, computed, default, data_type): ...
    def create_reference_attribute(self, class_name, name, mutable, reference): ...
    def create_collection_attribute(self, class_name, name, mutable): ...
    def create_mapped_collection_attribute(self, class_name, name, mutable, reference) -> None: ...

class PerSessionDefaultKeyMaker(ftrack_api.cache.KeyMaker): ...

memoise_defaults: Incomplete
memoise_session: Incomplete

class StandardFactory(Factory):
    def create(self, schema, bases: Incomplete | None = None): ...
    def create_mapped_collection_attribute(self, class_name, name, mutable, reference): ...
