import abc
import collections.abc
import ftrack_api.entity.base
from _typeshed import Incomplete

class Location(ftrack_api.entity.base.Entity):
    accessor: Incomplete
    structure: Incomplete
    resource_identifier_transformer: Incomplete
    priority: int
    def __init__(self, session, data: Incomplete | None = None, reconstructing: bool = False) -> None: ...
    def add_component(self, component, source, recursive: bool = True): ...
    def add_components(self, components, sources, recursive: bool = True, _depth: int = 0) -> None: ...
    def remove_component(self, component, recursive: bool = True): ...
    def remove_components(self, components, recursive: bool = True) -> None: ...
    def get_component_availability(self, component): ...
    def get_component_availabilities(self, components): ...
    def get_resource_identifier(self, component): ...
    def get_resource_identifiers(self, components): ...
    def get_filesystem_path(self, component): ...
    def get_filesystem_paths(self, components): ...
    def get_url(self, component): ...

class MemoryLocationMixin(ftrack_api.entity.base._EntityBase, collections.abc.MutableMapping, metaclass=ftrack_api.entity.base.DynamicEntityTypeMetaclass): ...
class UnmanagedLocationMixin(ftrack_api.entity.base._EntityBase, collections.abc.MutableMapping, metaclass=ftrack_api.entity.base.DynamicEntityTypeMetaclass): ...
class OriginLocationMixin(MemoryLocationMixin, UnmanagedLocationMixin, metaclass=abc.ABCMeta): ...

class ServerLocationMixin(ftrack_api.entity.base._EntityBase, collections.abc.MutableMapping, metaclass=ftrack_api.entity.base.DynamicEntityTypeMetaclass):
    def get_thumbnail_url(self, component, size: Incomplete | None = None): ...
