import ftrack_api.entity.base
from _typeshed import Incomplete

class User(ftrack_api.entity.base.Entity):
    def start_timer(self, context: Incomplete | None = None, comment: str = '', name: Incomplete | None = None, force: bool = False): ...
    def stop_timer(self): ...
    def send_invite(self) -> None: ...
    def reset_api_key(self): ...
