import collections.abc
from _typeshed import Incomplete

class Event(collections.abc.MutableMapping):
    def __init__(
        self,
        topic,
        id: Incomplete | None = None,
        data: Incomplete | None = None,
        sent: Incomplete | None = None,
        source: Incomplete | None = None,
        target: str = "",
        in_reply_to_event: Incomplete | None = None,
    ) -> None: ...
    def stop(self) -> None: ...
    def is_stopped(self): ...
    def __getitem__(self, key): ...
    def __setitem__(self, key, value) -> None: ...
    def __delitem__(self, key) -> None: ...
    def __iter__(self): ...
    def __len__(self) -> int: ...
