from _typeshed import Incomplete

class Parser:
    def __init__(self) -> None: ...
    def parse(self, expression): ...

class Expression:
    def match(self, candidate): ...

class All(Expression):
    def __init__(self, expressions: Incomplete | None = None) -> None: ...
    def match(self, candidate): ...

class Any(Expression):
    def __init__(self, expressions: Incomplete | None = None) -> None: ...
    def match(self, candidate): ...

class Not(Expression):
    def __init__(self, expression) -> None: ...
    def match(self, candidate): ...

class Condition(Expression):
    def __init__(self, key, operator, value) -> None: ...
    def match(self, candidate): ...
