name: PR

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - closed
      - converted_to_draft
      - ready_for_review
jobs:
  check-pr:
    name: Check PR
    uses: ftrackhq/ftrack-actions/.github/workflows/pr-base.yml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
      ftrackApiKey: ${{ secrets.FTRACK_API_KEY }}