name: ftrack python api CI test
on: [push]
jobs:

  strategy:
    max-parallel: 1
    fail-fast: false
    matrix:
      python-version: ["2.7", "3.6"]
      #python-version: ["2.7"]
      #python-version: ["2.7", "3.6", "3.7", "3.8", "3.9"]

  run-ftrack-test-server:
    runs-on: ubuntu-latest
    container: python:${{ matrix.python-version }}
    container: python:2.7

    services:
      ftrack:
        image: ftrackdocker/test-server:latest
        credentials:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        ports:
          - 80:80

    steps:         
      - name: Checkout api code
        uses: actions/checkout@v3
          
      - name: Test with pytest
        run: |
          python setup.py test
        env:
          FTRACK_SERVER: http://ftrack:80
          FTRACK_API_USER: ${{ secrets.FTRACK_API_USER }}
          FTRACK_API_KEY: ${{ secrets.FTRACK_API_KEY }}

