name: ftrack python api CI test
on: [push]
jobs:

  run-ftrack-test-server:
    runs-on: ubuntu-latest
    # container: ubuntu

    services:
      ftrackapp:
        image: ftrackdocker/test-server:latest
        credentials:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}  
        ports:
          - 80:80

    strategy:
      matrix:
        python-version: ["3.7"]

    steps:         
        
      - name: Checkout api code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Switch to Current Branch
        uses: actions/checkout@v3
        with:
          ref: ${{ env.BRANCH }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: update system
        run: |
          apt-get update
          apt-get install -y wget
          wget http://es.archive.ubuntu.com/ubuntu/pool/main/libf/libffi/libffi7_3.3-4_amd64.deb
          dpkg -i libffi7_3.3-4_amd64.deb
          export LD_LIBRARY_PATH=/lib:/usr/lib:/usr/local/lib
        
      - name: Test with pytest 
        run: |
          python setup.py test
        env:
          FTRACK_SERVER: http://ftrackapp:80
          FTRACK_API_USER: ${{ secrets.FTRACK_API_USER }}
          FTRACK_API_KEY: ${{ secrets.FTRACK_API_KEY }}
          
          
