name: API Unit Tests
on: [push]
jobs:
  run-tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["2.7", "3.6", "3.7", "3.8", "3.9"]
    runs-on: ubuntu-latest
    container: python:${{ matrix.python-version }}
    services:
      ftrack:
        image: ftrackdocker/test-server:latest
        credentials:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        ports:
          - 80:80
    steps:         
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run pytest
        run: |
          python setup.py test
        env:
          FTRACK_SERVER: http://ftrack:80
          FTRACK_API_USER: ${{ secrets.FTRACK_API_USER }}
          FTRACK_API_KEY: ${{ secrets.FTRACK_API_KEY }}

