name: ftrack python api CI test
on: [push]
jobs:

  run-ftrack-test-server:
    runs-on: ubuntu-latest

    services:
      ftrackapp:
        image: ftrackdocker/test-server:latest
        credentials:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}  
        ports:
          - 80:80

    strategy:
      max-parallel: 1
      matrix:
        python-version: ["3.7", "3.8", "3.9"]

    steps:         

      - name: Checkout api code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ env.BRANCH }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          check-latest: true
          
      - name: Test with pytest 
        run: |
          pip install wheel
          python setup.py test
        env:
          FTRACK_SERVER: http://localhost:80
          FTRACK_API_USER: ${{ secrets.FTRACK_API_USER }}
          FTRACK_API_KEY: ${{ secrets.FTRACK_API_KEY }}
          
          
        
