name: ftrack python api CI test

on: [push]

jobs:
  run-ftrack-test-server:
    runs-on: ubuntu-latest
        
    steps:  
      - name: Checkout 
        uses: actions/checkout@v2 # Required to mount the Github Workspace to a volume 

      - name: Run the ftrack server
        uses: addnab/docker-run-action@v3
        with:
          image: ftrackdocker/test-server:latest
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
