name: ftrack python api CI test

on: [push]

jobs:
  run-ftrack-test-server:
    runs-on: ubuntu-latest
        
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
