name: ftrack python api CI test

on: [push]

jobs:
  run-ftrack-test-server:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:  
      - name: Run the ftrack server
        uses: addnab/docker-run-action@v3
        with:
          image: ftrackdocker/test-server:latest
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
  run-python-tests:
    runs-on: ubuntu-latest
    needs: run-ftrack-test-server

    strategy:
      matrix:
        python-version: ["3.7", "3.8"]
        
    steps:  

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Switch to Current Branch
        run: git checkout ${{ env.BRANCH }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          
      - name: install api
        run: |
          python -m pip install .
          
      - name: Test with pytest
        run: |
          python setup.py test
        env:
          FTRACK_SERVER: ${{ secrets.FTRACK_SERVER }}
          FTRACK_API_USER: ${{ secrets.FTRACK_API_USER }}
          FTRACK_API_KEY: ${{ secrets.FTRACK_API_KEY }}
          
          
        
