name: ftrack python api CI test

on: [push]

jobs:
  run-ftrack-test-server:
    runs-on: ubuntu-latest
      container: 
      image: ftrackdocker/test-server:latest
      env: 
        username: $DOCKER_HUB_USERNAME
        password: $DOCKER_HUB_PASSWORD
        email: $DOCKER_HUB_EMAIL
